auth5app/urls.py
from django.conf.urls import url
from auth5app import views

# Template urls!
app_name = 'auth5app'


urlpatterns =[
    url(r'^register/$',views.register,name='register'),
    url(r'^login/$',views.user_login,name='user_login'),

]

auth5pro/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from auth5app import views
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^auth5app/',include('auth5app.urls')),
    url(r'^logout/$',views.user_logout ,name='user_logout'),
    url(r'special/',views.special, name='special'),
]

auth5app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    # additional
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

auth5app/forms.py
from django import forms
from auth5app.models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileFormInfo(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

auth5app/views.py
from django.shortcuts import render
from auth5app.forms import UserForm,UserProfileFormInfo

#
from django.contrib.auth import authenticate ,login, logout
from django.http import HttpResponseRedirect ,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,'mood1/index.html')


@login_required
def special(request):
    return HttpResponse("You are logged in , Nice!")


@login_required()
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':
        user_form= UserForm(data=request.POST)
        profile_form = UserProfileFormInfo(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic =request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileFormInfo()

    return render(request , 'mood1/registration.html',{'user_form':user_form,
                                                       'profile_form':profile_form,
                                                       'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username , password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account Not Active")
        else:
            print("Someone Tried Login AND Failed!")
            print("Username:{} and Password{}".format(username,password))
            return HttpResponse("invalid login details supplied!")
    else:
        return render(request ,'mood1/login.html',{})

templates/mood1/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>




</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <ul class="nav navbar-nav">

            <li><a class="navbar-brand" href="{% url 'index'%}">BASUNBUL.CO</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="navbar-link" href="{% url 'auth5app:register' %}">Register</a></li>
            {% if user.is_authenticated %}
                <li><a class="navbar-link" href="{% url 'user_logout' %}">Logout</a></li>
                {% else %}
                <li><a class="navbar-link" href="{% url 'auth5app:user_login' %}">Login</a></li>
            {% endif %}

        </ul>
    </div>
</nav>
<div class="container">
    {% block body_block %}

    {% endblock %}

</div>

</body>
</html>

templates/mood1/index.html
<!DOCTYPE html>
{% extends "mood1/base.html" %}
{% block body_block %}
<div class="jumbotron">
<h1>Welcom To BASUNBUL Market:</h1>
</div>
{% endblock %}

templates/mood1/login.html
<!DOCTYPE html>
{% extends 'mood1/base.html' %}

{% block body_block %}
    <div class="jumbotron">
    <h1>Please Login </h1>
        <form action="{% url 'auth5app:user_login' %}" method="POST">
            {% csrf_token %}
            <label for="username">UserName:</label>
            <input type="text" name="username" palceholder="Enter Uasr Name">
            <label for="password">Password:</label>
            <input type="password" name="password" placeholder="Enter Password max-9">
            <input type="submit" name="Login" value="Login">

        </form>

    

    </div>

{% endblock %}

templates/mood1/registration.html
<!DOCTYPE html>
{% extends 'mood1/base.html' %}
{% load static %}

{% block body_block %}
<div class="jumbotron">
{% if registered %}
    <h1>Thank you for registering!</h1>
    {% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the form:</h3>

    <form enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
        <input type="submit" name="" value="Register">

    </form>
{% endif %}
</div>
{% endblock %}